openapi: 3.2.0
info:
  title: BigCommerce Customer Login (SSO) Login Token API
  description: "Enable single sign-on for shoppers on BigCommerce hosted storefronts.\n\n[Learn more about the customer login API](/docs/start/authentication/customer-login).\n\nFor info about API accounts, see our [Guide to API Accounts](/docs/start/authentication/api-accounts).\n    \nFor info about authenticating BigCommerce APIs, see [Authentication and Example Requests](/docs/start/authentication#user-generated-jwts)."
  termsOfService: https://www.bigcommerce.com/terms
  contact:
    name: BigCommerce
    url: https://www.bigcommerce.com
    email: support@bigcommerce.com
  version: ''
servers:
- url: https://{store_domain}
  variables:
    store_domain:
      default: your_store.example.com
      description: The [URL authority](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#authority) of the storefront.
tags:
- name: Login Token
paths:
  /login/token/{jwt_token}:
    get:
      tags:
      - Login Token
      summary: BigCommerce Login Token
      operationId: getCustomerLogin
      description: 'The customer login access point URL.


        [Learn more about the Customer Login API](/docs/start/authentication/customer-login).


        ## Example


        ```

        https://yourstore.example.com/login/token/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ7Y2xpZW50X2lkfSIsImlhdCI6MTUzNTM5MzExMywianRpIjoie3V1aWR9Iiwib3BlcmF0aW9uIjoiY3VzdG9tZXJfbG9naW4iLCJzdG9yZV9oYXNoIjoie3N0b3JlX2hhc2h9IiwiY3VzdG9tZXJfaWQiOjJ9.J-fAtbjRFGdLsT744DhoprFEDqIfVq72HbDzrbFy6Is

        ```'
      parameters:
      - name: jwt_token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
